const GET_FAIL="GET_FAIL";
const GET_SUCCESS="GET_SUCCESS";
const GET_REQUEST="GET_REQUEST";
const USER_SIGNIN="USER_SIGNIN";
const USER_SIGNOUT="USER_SIGNOUT";
const ADD_TO_CART="ADD_TO_CART";
const REMOVE_FROM_TYPE="REMOVE_FROM_TYPE"
const SHIPPING_ADDRESS="SHIPPING_ADDRESS"
const SAVE_PAYMENT_METHOD="SAVE_PAYMENT_METHOD"
const CLEAR_CART="CLEAR_CART"

export{CLEAR_CART,GET_FAIL,GET_SUCCESS,GET_REQUEST,USER_SIGNIN,USER_SIGNOUT,ADD_TO_CART,REMOVE_FROM_TYPE,SHIPPING_ADDRESS,SAVE_PAYMENT_METHOD}